### PR TITLE
brcmfmac: Fix AP mode

### PR DESCRIPTION
**Pull request by pblass**
Fix access point mode by bringing firmware into appropriate state before setting up the device.

### CODE REVIEW

**Comment by jannau** [comment]
This doesn't seem to work on the M1 Mac mini, PCI id `14e4:4425`, subsystem: `106b:4378`
```
[  952.837442] ieee80211 phy0: brcmf_fweh_call_event_handler: no interface object
[  952.923506] IPv6: ADDRCONF(NETDEV_CHANGE): wlp1s0f0: link becomes ready
[  984.462888] ieee80211 phy0: brcmf_vif_set_mgmt_ie: vndr ie set error : -52
[  984.464284] ieee80211 phy0: brcmf_vif_set_mgmt_ie: vndr ie set error : -52
[ 1018.289793] ieee80211 phy0: brcmf_fweh_call_event_handler: no interface object
[ 1018.357895] IPv6: ADDRCONF(NETDEV_CHANGE): wlp1s0f0: link becomes ready
[ 1050.787938] ieee80211 phy0: brcmf_vif_set_mgmt_ie: vndr ie set error : -52
[ 1050.789201] ieee80211 phy0: brcmf_vif_set_mgmt_ie: vndr ie set error : -52
```
That's the result of setting a shared wlan through KDE's NetworkManager setting dialog.

**Comment by jannau** [comment]
The errors seem unrelated. AP mode works on the M1 Mac Mini. BCM4378 and BCM4387 are the only 2 supported models on Apple silicon macs. The WiFi 6E variant  BCM4388 on most models released 2023 is not working.

Any idea on which chipsets this is required? On the Cypress CYW43455 used on Raspberry Pi 4s it is apparently not needed.

**Comment by pblass** [comment]
> Any idea on which chipsets this is required? On the Cypress CYW43455 used on Raspberry Pi 4s it is apparently not needed.

No, unfortunately not. This is based on bcmdhd-4359 which does not differentiate between 4378/4387/4388 chipsets for this as far as I can tell. It only checks if AP mode is configured and then triggers the role change. There are some weird exceptions for different chipsets though.

**Comment by marcan** [comment]
FWIW, I tried emailing the Cypress people with questions (to avoid breaking their chips) and they ignored me, so as far as I'm concerned it's okay if we break them. If someone wants to step up to maintain support for CYW parts, they can do so, but it's not our job to care about them if the "official" maintainers don't.

Manually pulled this into the bits branch, should be in the next tag. Thanks!

**Pull request closed without merging**
