### PR TITLE
New audio bit

### PR DESCRIPTION
**Pull request by povik**
Sound driver update!

DTs to go with it: https://github.com/povik/linux/tree/bits-update/000-devicetree
(fixups on top of current bits/000-devicetree, you will need to squash 'arm64: dts: apple: t8103-j313: Also disable speakers' to cleanly take up the fixups)

# Changes

The ALSA card now has devices `Primary`/`hw:0,0` and `Secondary`/`hw:0,1`. Routing of audio from the devices to speakers/headphones depends on the state of the card's controls (those seen in alsamixer). By default both headphones/speakers are routed to the primary device, with one or the other being enabled based on the plug state of the jack connector. You can override that. **To drive all the speakers on large (>2ch) speaker arrays, you need to use the secondary device.** So you set the `Speaker Playback Mux` to `Secondary`, then stream audio to `hw:0,1`. This is because the primary device has some parameters set to appease the jack codec -- this limitation may be lifted in the future.

Anyway, such details should be hidden in proper userspace configuration, which we have yet to write.

## Speakers

The machine driver now sets volume caps and locks some other controls. This is done in a [`fixup_controls` method](https://github.com/povik/linux/blob/5952de58993c87e5e5797ac37ef4f7364ac5ef37/sound/soc/apple/macaudio.c#L719) specific to each machine model. I have written those for j274 (Mac mini) and j314/316 (2021 Macbook Pros), but for the other models it is missing. The driver refuses probe if all: 1. the method is missing for the model in question, 2. speakers are enabled in DT, and 3. `snd-soc-macaudio.void_warranty=1` isn't passed to the kernel.

You can help write the methods by obtaining a trace of macOS booting and doing playback on the speakers with the `hv/trace_codecs.py` script. This is really just to see what volume level macOS sets. (Ideally you take the trace with setting the full user volume in macOS, although it appears macOS doesn't propagate the user volume into codecs to any extent.)

### J314

 * We now set the OCE_RETRY bit on TAS2764 speaker amps so that they retry unmute after an overcurrent event. This is to counter the dropouts of old. The other workaround didn't prove solid.

 * The 'DC blocker' highpass filter of the speaker amps is now exported to userspace for the woofers and locked at 800 Hz for the tweeters.

## CS42L84 driver *NEW!*

With the CS42L84 driver we should now have jack support everywhere (hooray!), that is pending the DTs are correct. The driver was tested on j314. It is able of both playback and capture. The mic detection is hand-rolled by me, it is at the moment limited to CTIA (non-China) wiring of the jack, and it is plausible there are issues with it.

## Other changes (that I can think of right now)

 * Machine driver name (important for userspace to lock on) is now `snd-soc-macaudio`

 * J314/J316 now have distinct model strings on the ALSA card

 * The jack codec now has 'Jack' prefix on controls on all machines (was not uniform before). This will upset some people's volume settings.

### CODE REVIEW

**Comment by povik** [comment]
Wrote fixup_controls for mac studio and pushed additional DT fixups (added jack node on mac studio, fixed M2 devices)

**Comment by povik** [comment]
Pushed some more DT edits

**Review by sh7dm — COMMENTED** [review]
One of the important things to do might be removing userspace I2C access (provided by the `i2c-dev` driver). Please check, but I am pretty sure that when probing i2c-dev module you can access buses where amps are from userspace. Because of this issue programs not even intended to access the amp could do this (like lm-sensors which warns a bit about the risk of tripping some important registers, though I guess it should be same for TAS2764 amps). Also users or malicious software could access internal settings causing issues. This violates the safety guarantees `macaudio` provides.

Also, there's just no sane use for userspace-accessible internal buses, since user cannot attach anything new there (well, one who could solder something in there and make it work should be able to tinker with kernel/DT):
- If somebody wants to set a config option which isn't accessible from the TAS2764 kernel driver, they probably know enough to do a proper implementation instead of a hacky userspace semi-driver.
- If user wants to void the warranty (remove volume and frequency locks), they have to enable corresponding parameter knowing and taking the responsibility.
- In any case when somebody changes codec parameters via register access and not the driver, ALSA settings become different from real settings. This is an invalid behavior, so nobody must rely on such configurations.

I think an I2C subsystem change has to be done to remove some buses from `/dev/i2c-*`. Current [`i2c-dev.c`](https://github.com/torvalds/linux/blob/42e66b1cc3a070671001f8a1e933a80818a192bf/drivers/i2c/i2c-dev.c) code seems to attach to whatever adapter becomes available.

So a solution would be to add a DT prop onto the I2C controller node (such as `internal`), which then propagates into the adapter settings (gets a special property). `i2c-dev` could be made not to use devices marked as internal after this change.

This is not a blocker to this patchset.

**Comment by povik** [comment]
> One of the important things to do might be removing userspace I2C access (provided by the i2c-dev driver). Please check, but I am pretty sure that when probing i2c-dev module you can access buses where amps are from userspace. Because of this issue programs not even intended to access the amp could do this (like lm-sensors which warns a bit about the risk of tripping some important registers, though I guess it should be same for TAS2764 amps). Also users or malicious software could access internal settings causing issues. This violates the safety guarantees macaudio provides.

I will check but I expect direct userspace access to I2C devices which have a driver attached on the kernel side is prohibited.

**Comment by povik** [comment]
Yeah, indeed 

    $ sudo i2cdump 1 0x31
    No size specified (using byte-data access)
    Error: Could not set address to 0x31: Device or resource busy

Not sure what happens though if the coded driver is disabled, I assume the kernel does not prohibit access from userspace then.

**Comment by dsseng** [comment]
What's if `i2c-dev` is probed first? Nothing if no program has already attached to the address?

**Comment by marcan** [comment]
Done, thanks!

**Pull request closed without merging**
