### PR TITLE
Create ane_accel.h

### PR DESCRIPTION
**Pull request by yoonjin2**

### CODE REVIEW

**Comment by eiln** [comment]
1. We need DCO. Please use `git commit -s`
2. UAPI isn't stable. It's not upstreamed for a reason.

**Comment by yoonjin2** [comment]
Yup, thnx.

Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________

**Comment by yoonjin2** [comment]
But Apple NPU hqs quite differsnt architecture; we should not get this into classical apporach. :) I don't know why dafuq they don't merge it, but I think we should add this pull request into freedesktop gitlab. Thanks ;)

**Comment by yoonjin2** [comment]
This is quite strange, becayse it still fails though I use git commit -s

**Pull request closed without merging**
