### PR TITLE
ARM64_MEMORY_MODEL_CONTROL missing when selecting ARCH_APPLE

### PR DESCRIPTION
**Pull request by Perpixel**
Add select ARM64_MEMORY_MODEL_CONTROL

### CODE REVIEW

**Comment by marcan** [comment]
I don't think this necessarily should be a default feature for the arch? It's completely optional.

**Comment by Perpixel** [comment]
It doesn't compile without it. It's a bug?

**Comment by jannau** [comment]
> It doesn't compile without it. It's a bug?

that should be fixes, not sure if already in asahi-6.4-6 or only in asahi-wip

**Comment by Perpixel** [comment]
It does work from today's commit.

**Pull request closed without merging**
