### PR TITLE
Mailbox WIP to discuss how we will implement RTKit

### PR DESCRIPTION
**Pull request by svenpeter42**
untested i think and still has some rough edges. mostly split off from a more complex driver that handled all endpoints internally so there's even a chance that this will work ;)

this uses the mailbox regs starting at 0x800 and exposes up to 256 channels for different clients. just ignore the tracepoint boilerplate

### CODE REVIEW

**Comment by alyssarosenzweig** [comment]
> when a message is sent. With TXDONE_DIRECT those messages can be
> acknowledge immediately and there's no need to enable the interrupt

acknowledged

**Comment by pipcet** [comment]
Here's the main problem I see: endpoints aren't independent. EP0 is special and magic, and needs to control whether or not the other endpoints can even be allowed to send messages to the IOP.

For example, when you start up an endpoint (and we really don't want to start endpoints we don't know how to handle, IMHO), you need to send a message to endpoint 0. I think that should happen automatically when the actual per-endpoint messaging channel (which may or may not be a mailbox) is opened.

**Comment by svenpeter42** [comment]
This code doesn't deal with the application plane. It just implements the HW FIFO and muxes it into different endpoints. Whatever part implements that application plane (which is different for e.g. SEPOS and RTKit) will have to deal with the magic EP0.

**Comment by pipcet** [comment]
> This code doesn't deal with the application plane.

It constrains what the application plane can do, though. Even if we assume a fixed useless epmap (which I'm not convinced is a good strategy), everything that talks to an endpoint needs to talk to EP0 first. That means all drivers using this mailbox will have to talk to the (single, by the design of the mailbox) driver talking to EP0. They'll have to know about it. They'll also have to know about the panic endpoint to know when to stop sending messages and corrupting debug state.

So the endpoints all end up knowing about each other, and the abstraction the mailbox provides does indeed become useless. (Putting everything into one huge monster driver is a bad idea).

I really think it's cleaner to go "through" a muxing/demuxing ASC driver that knows what the state of the IOP is, as my sketch code does: Those endpoints that need to do more than open a channel and talk to it grab a reference to that ASC (I used a remoteproc since the main example is the panic endpoint which simply crashes the remoteproc). The ASC driver can send and receive data for all endpoints (I think it's very probable we're going to need that at some point to work around broken firmware, or to handle initialization phases better); it initializes endpoints when a client connects, it has all the timing data, and it knows when to stop 
sending messages because the ASC crashed.

And we don't even have to invent hardware to put into the devicetree, because conveniently there's that start-CPU bit that's on a different page and can be the `reg` property of the ASC driver.

> It just implements the HW FIFO
> and muxes it into different endpoints.

So it "just" does two things. I'm saying it should do one.

> Whatever part implements that application plane (which is different for e.g. SEPOS and RTKit) will have to deal with the magic EP0.

Is the mgmt endpoint different for SEPOS? I haven't looked at it at all.

Sorry this got a bit long, but you said you wanted a discussion. I hope my point got across, which is that endpoints are not reasonably independent.

**Pull request closed without merging**
