### PR TITLE
drm: apple: backlight: force backlight update after resume

### PR DESCRIPTION
**Pull request by kettenis**
If the DCP firmware indicates that it didn't restore the brightness, schedule an update.  Wait for 1 frame duration and check if the brightness update has been taken care of by a swap that happened in the meantime.
Fixes restoring the brightness after resume when running on a dumb framebuffer where swaps may not happen for a very long time.

### CODE REVIEW

**Comment by kettenis** [comment]
@jannau This implements the idea we discussed a few days ago on icb. Seems to work on OpenBSD. Not even sure this compiles on linux ;)

**Comment by jannau** [comment]
looks good to me, thanks

**Comment by jannau** [comment]
merged into https://github.com/jannau/linux/tree/beta-6.8/asahi-wip, thanks

**Comment by jannau** [comment]
merged in asahi-wip / asahi-6.8.8-1

**Pull request closed without merging**
